/* eslint-disable @next/next/no-sync-scripts */
import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import Script from 'next/script';
import { Suspense } from 'react';
import { Toaster } from 'sonner';

import './globals.css';

import AppleProvider from '@components/common/AppleProvider';
import QueryClientProviders from '@components/common/QueryClientProvider';
import WebViewContainer from '@components/common/WebViewContainer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

const nanumSquareRound = localFont({
  src: [
    {
      path: './fonts/NanumSquareRoundL.woff2',
      weight: '300',
    },
    {
      path: './fonts/NanumSquareRoundR.woff2',
      weight: '400',
    },
    {
      path: './fonts/NanumSquareRoundB.woff2',
      weight: '500',
    },
    {
      path: './fonts/NanumSquareRoundEB.woff2',
      weight: '700',
    },
  ],
  variable: '--font-nanum-square-round',
});

const KAKAO_APP_KEY = process.env.NEXT_PUBLIC_KAKAO_APP_KEY;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryClientProviders>
      <WebViewContainer />
      <html lang="en" className={`${nanumSquareRound.variable}`}>
        <head></head>
        <body className="relative overscroll-y-none min-h-[100dvh] w-full max-w-[480px] mx-auto scrollbar-hide">
          <Suspense>{children}</Suspense>
          <Script
            src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${KAKAO_APP_KEY}&libraries=services,clusterer&autoload=false`}
            strategy="beforeInteractive"
          />
          <Script
            type="text/javascript"
            src="https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js"
            strategy="beforeInteractive"
          />
          <AppleProvider />
          <Toaster
            duration={2000}
            position="bottom-center"
            toastOptions={{
              unstyled: true,
              classNames: {
                toast:
                  'bg-system-dim60 text-white w-full h-[56px] p-[12px] flex items-center justify-center rounded-[16px] body-16-bold font-sans',
              },
            }}
          />
        </body>
      </html>
    </QueryClientProviders>
  );
}
